### ISSUE TITLE
Failed to build bb-remote-execution on Windows

### ISSUE THREAD

**Issue by Jasper-Li** [buildbarn/bb-remote-execution#102]
env: Windows 10 64bit 

build cmd on powershell

>  bazel build --platforms=@io_bazel_rules_go//go/toolchain:windows_amd64 //...

output error:

```
Loading: 
Loading: 0 packages loaded
INFO: Repository com_github_bazelbuild_remote_apis instantiated at:
  E:/git/buildbarn/bb-remote-execution/WORKSPACE:45:16: in <toplevel>
  E:/git/buildbarn/bb-remote-execution/go_dependencies.bzl:149:18: in go_dependencies
Repository rule go_repository defined at:
  C:/users/10172740/_bazel_10172740/rpt2bk7z/external/bazel_gazelle/internal/go_repository.bzl:214:32: in <toplevel>
DEBUG: C:/users/10172740/_bazel_10172740/rpt2bk7z/external/bazel_gazelle/internal/go_repository.bzl:209:18: com_github_bazelbuild_remote_apis: gazelle: rule @bazel_remote_apis//build/bazel/remote/asset/v1:asset imports "github.com/bazelbuild/remote-apis/build/bazel/remote/execution/v2" which matches multiple rules: @bazel_remote_apis//build/bazel/remote/execution/v2:remote_execution_go_proto and @bazel_remote_apis//build/bazel/remote/execution/v2:execution. # gazelle:resolve may be used to disambiguate
gazelle: rule @bazel_remote_apis//build/bazel/remote/execution/v2:execution imports "github.com/bazelbuild/remote-apis/build/bazel/semver" which matches multiple rules: @bazel_remote_apis//build/bazel/semver:semver_go_proto and @bazel_remote_apis//build/bazel/semver. # gazelle:resolve may be used to disambiguate
ERROR: An error occurred during the fetch of repository 'com_github_bazelbuild_remote_apis':
   Traceback (most recent call last):
	File "C:/users/10172740/_bazel_10172740/rpt2bk7z/external/bazel_gazelle/internal/go_repository.bzl", line 212, column 10, in _go_repository_impl
		patch(ctx)
	File "C:/users/10172740/_bazel_10172740/rpt2bk7z/external/bazel_gazelle/internal/go_repository.bzl", line 310, column 17, in patch
		fail("Error applying patch %s:\n%s%s" %
Error in fail: Error applying patch @com_github_buildbarn_bb_storage//:patches/com_github_bazelbuild_remote_apis/golang.diff:
Assertion failed: hunk, file ../patch-2.5.9-src/patch.c, line 354
patching file build/bazel/remote/asset/v1/BUILD
ERROR: E:/git/buildbarn/bb-remote-execution/WORKSPACE:45:16: fetching go_repository rule //external:com_github_bazelbuild_remote_apis: Traceback (most recent call last):
	File "C:/users/10172740/_bazel_10172740/rpt2bk7z/external/bazel_gazelle/internal/go_repository.bzl", line 212, column 10, in _go_repository_impl
		patch(ctx)
	File "C:/users/10172740/_bazel_10172740/rpt2bk7z/external/bazel_gazelle/internal/go_repository.bzl", line 310, column 17, in patch
		fail("Error applying patch %s:\n%s%s" %
Error in fail: Error applying patch @com_github_buildbarn_bb_storage//:patches/com_github_bazelbuild_remote_apis/golang.diff:
Assertion failed: hunk, file ../patch-2.5.9-src/patch.c, line 354
patching file build/bazel/remote/asset/v1/BUILD
ERROR: no such package '@com_github_bazelbuild_remote_apis//': Error applying patch @com_github_buildbarn_bb_storage//:patches/com_github_bazelbuild_remote_apis/golang.diff:
Assertion failed: hunk, file ../patch-2.5.9-src/patch.c, line 354
patching file build/bazel/remote/asset/v1/BUILD
INFO: Elapsed time: 1.069s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
FAILED: Build did NOT complete successfully (0 packages loaded)

```
From logs, It seems somthing wrong on patching. Do I need some other configurations on Windows 10?

**Comment by EdSchouten** [comment]
Could this be related? https://stackoverflow.com/questions/23891281/assertion-failed-when-using-patch-exe-of-git-for-windows

I have never attempted to build Buildbarn on Windows; also don't own a Windows machine, so I can't easily reproduce. I think it may generally be easier to just build executables for Windows from a Linux or Mac machine. You can use a command like this:

```sh
bazel build --platforms=@io_bazel_rules_go//go/toolchain:windows_amd64 //cmd/bb_worker
```

**Comment by EdSchouten** [comment]
Closing this due to inactivity. Feel free to reopen if needed. Thanks!
